version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        networks:
            - app-network

    nginx:
        image: nginx:latest
        volumes:
            - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        ports:
            - "80:80"
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge 